### PR TITLE
adds a second completion handler onDismiss versus onTap so you can handle both results

### PR DESCRIPTION
**Pull request by isupremedyou**
adds a second completion handler onDismiss versus onTap so you can handle both results

### CODE REVIEW

**Comment by travischapman** [comment]
merged

**Comment by schmidyy** [comment]
I think it’s good to have one closure be called wether the Loaf is tapped or dismissed after the delay. What’s the use case for this?

**Comment by isupremedyou** [comment]
If the user taps on the Loaf you may want to handle the interaction differently. One example may be using loafs for displaying push notifications when the app is in the foreground. If the user taps on a loaf, a completion block may be based in for navigation, but if they do not tap on the notification, you could have it do something else/nothing.

I suppose at the very least onTap should not be called when the view isn't actually being tapped as it is currently in the dispatch item on line 257 of Loaf.swift

**Comment by schmidyy** [comment]
Hmm, this is actually a good point which I hadn’t thought of. 

Instead of having 2 closures to define, what do you think of having one closure (named like `completionHandler`) but it also would have a Boolean parameter (like `wasTaped:`) which the user can chose to consider. 

Thanks for your feedback!

**Comment by schmidyy** [comment]
I resolved this here https://github.com/schmidyy/Loaf/commit/aa438d4b36ec30fc9a2e7b1299265ac31c21530d

**Pull request closed without merging**
